name: Release - Windows-x86_64

on:
  push:
    tags-ignore:
      - "nightly*"

runs:
    using: "composite"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: both
          target: x86_64-pc-windows-msvc
          args: "--release"
          strip: true

      - name: Create ZIP (Windows)
        run: |
          Compress-Archive -Path target/x86_64-pc-windows-msvc/release/rs.exe -Destination rs-windows-x86_64.zip
          if (!(Test-Path -Path "builds")) {
            New-Item -ItemType Directory -Path "builds"
          }
          Move-Item -Path rs-windows-x86_64.zip -Destination "builds/"

      - name: "Upload Artifact"
        uses: actions/upload-artifact@v3
        with:
          name: release-builds
          path: builds/rs-windows-x86_64.zip
          retention-days: 1
