name: Release - FreeBSD-x86_64

on:
  push:
    tags-ignore:
      - "nightly*"

runs:
    using: "composite"
    steps:
    - uses: actions/checkout@v3
    - name: Build in FreeBSD
      uses: vmactions/freebsd-vm@v0
      with:
        release: 13.1
        usesh: true
        prepare: |
          pkg install -y rust zip

        run: |
          cargo build --release
          mkdir -p builds
          zip -j rs-freebsd-x86_64.zip target/release/rs
          zip -r rs-freebsd-x86_64.zip static
          mkdir -p builds
          mv rs-freebsd-x86_64.zip builds/
          cargo clean

    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: release-builds
        path: builds/rs-freebsd-x86_64.zip
        retention-days: 1
