name: Deploy Nightly

on: [push]

jobs:
  build:
    name: Release - ${{ matrix.platform.release_for }}
    strategy:
      matrix:
        platform:
          - release_for: FreeBSD-x86_64
            os: ubuntu-20.04
            target: x86_64-unknown-freebsd
            bin: rs
            name: rs-freebsd-x86_64
            command: build

          - release_for: Windows-x86_64
            os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: rs.exe
            name: rs-windows-x86_64.exe
            command: both

          - release_for: macOS-x86_64
            os: macOS-latest
            target: x86_64-apple-darwin
            bin: rs
            name: rs-darwin-x86_64
            command: both


    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v0
        with:
          command: ${{ matrix.platform.command }}
          target: ${{ matrix.platform.target }}
          args: "--release"
          strip: true
      - name: Create ZIP
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            Compress-Archive -Path target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }} -Destination ${{ matrix.platform.name }}.zip
            mkdir -p builds
            mv ${{ matrix.platform.name }}.zip builds/
          else
            zip -r ${{ matrix.platform.name }}.zip target/${{ matrix.platform.target }}/release/${{ matrix.platform.bin }}
            mkdir -p builds
            mv ${{ matrix.platform.name }}.zip builds/
          fi

  deploy:
    name: Deploy Nightly
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - name: Update Nightly Release
        uses: andelf/nightly-release@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: nightly
          name: 'Deploy Nightly $$'
          prerelease: true
          body: 'TODO: Add nightly release notes'
          files: |
            ./builds/*.zip
