name: Build and Release

on:
  push:
    tags-ignore:
      - 'nightly*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Windows Release
        uses: ./.github/workflows/deployment/release/windows

  build-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build MacOs Release
        uses: ./.github/workflows/deployment/release/macos

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Linux Release
        uses: ./.github/workflows/deployment/release/linux

  # build-freebsd:
  #   runs-on: macos-12
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v3
  #
  #     - name: Build FreeBSD Release
  #       uses: ./.github/workflows/deployment/release/freebsd


  deploy:
    name: Deploy Release
    needs:
      - build-windows
      - build-macos
      - build-linux
      # - build-freebsd
    runs-on: ubuntu-20.04
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: release-builds
        path: builds
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "builds/*.zip"
