name: Build and Release

on:
  push:
    tags-ignore:
      - 'nightly*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Build Windows Release
        uses: ./.github/workflows/deployment/release/windows
  build-macos:
    runs-on: macos-latest
    steps:
      - name: Build MacOs Release
        uses: ./.github/workflows/deployment/release/macos
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Build Linux Release
        uses: ./.github/workflows/deployment/release/linux
  # freebsd:


  deploy:
    name: Deploy Release
    needs:
      - build-windows
      - build-macos
      - build-linux
    runs-on: ubuntu-20.04
    steps:
    - name: Download a single artifact
      uses: actions/download-artifact@v3
      with:
        name: release-builds
        path: builds
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "builds/*.zip"
